# Generated by Django 4.2 on 2023-04-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelquiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answers',
            field=models.JSONField(default=dict),
        ),
    ]
